local M = {}

M.PLAYER_ACCELERATION = 3500 
M.AIR_FRICTION = 0.5
M.PLAYER_FRICTION = 3
M.PLAYER_MAX_SPEED = 450
M.PLAYER_WALL_FRICTION = 0.9

M.GRAVITY = 1000
M.JUMP_ACCELERATION = 650
M.WALL_JUMP_ACCELERATION = 500

return M

